name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  compile-cubiomes:
    name: Compile Cubiomes to shared library
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      SRC_FILES: noise.c biomes.c layers.c biomenoise.c generator.c finders.c util.c quadbase.c loot/items.c loot/loot_functions.c loot/loot_tables.c loot/loot_table_context.c loot/loot_table_parser.c loot/loot_tables/bastion_bridge_1_16_1.c loot/loot_tables/bastion_bridge_1_16_5.c loot/loot_tables/bastion_bridge_1_20.c loot/loot_tables/bastion_other_1_16_1.c loot/loot_tables/bastion_other_1_16_5.c loot/loot_tables/bastion_other_1_20.c loot/loot_tables/bastion_other_1_21_1.c loot/loot_tables/buried_treasure_1_13.c loot/loot_tables/buried_treasure_1_18.c loot/loot_tables/desert_pyramid_1_13.c loot/loot_tables/desert_pyramid_1_20.c loot/loot_tables/end_city_treasure_1_13.c loot/loot_tables/end_city_treasure_1_20.c loot/loot_tables/igloo_chest_1_13.c loot/loot_tables/jungle_temple_1_13.c loot/loot_tables/jungle_temple_1_14.c loot/loot_tables/jungle_temple_1_20.c loot/loot_tables/jungle_temple_dispenser_1_13.c loot/loot_tables/nether_bridge_1_13.c loot/loot_tables/nether_bridge_1_20.c loot/loot_tables/pillager_outpost_1_14.c loot/loot_tables/pillager_outpost_1_19_2.c loot/loot_tables/pillager_outpost_1_20.c loot/loot_tables/ruined_portal_1_16_1.c loot/loot_tables/ruined_portal_1_21_5.c loot/loot_tables/shipwreck_map_1_13.c loot/loot_tables/shipwreck_map_1_18.c loot/loot_tables/shipwreck_map_1_20.c loot/loot_tables/shipwreck_supply_1_13.c loot/loot_tables/shipwreck_supply_1_14.c loot/loot_tables/shipwreck_supply_1_17.c loot/loot_tables/shipwreck_supply_1_20.c loot/loot_tables/shipwreck_treasure_1_13.c loot/loot_tables/shipwreck_treasure_1_20.c loot/cjson/cJSON.c
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Compile shared library (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        working-directory: src/main/c/cubiomes
        run: gcc -shared -o ../../resources/libcubiomes.so $SRC_FILES -O3 -fPIC
      - name: Compile shared library (macos-latest)
        if: matrix.os == 'macos-latest'
        working-directory: src/main/c/cubiomes
        run: |
          gcc -shared -o ../../resources/libcubiomes_arm64.dylib -arch arm64 $SRC_FILES -O3 -fPIC
          gcc -shared -o ../../resources/libcubiomes_x86_64.dylib -arch x86_64 $SRC_FILES -O3 -fPIC
          lipo -create -output ../../resources/libcubiomes.dylib ../../resources/libcubiomes_arm64.dylib ../../resources/libcubiomes_x86_64.dylib
      - name: Compile shared library (windows-latest)
        if: matrix.os == 'windows-latest'
        working-directory: src/main/c/cubiomes
        run: |
          $src = $env:SRC_FILES.Split(" ")
          gcc -shared -o ../../resources/cubiomes.dll $src -O3

      - name: Compute SHA256 hash (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: sha256sum src/main/resources/libcubiomes.so
      - name: Compute SHA256 hash (macos-latest)
        if: matrix.os == 'macos-latest'
        run: shasum -a 256 src/main/resources/libcubiomes.dylib
      - name: Compute SHA256 hash (windows-latest)
        if: matrix.os == 'windows-latest'
        run: Get-FileHash -Algorithm SHA256 src/main/resources/cubiomes.dll

      - name: Capture shared library (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: libcubiomes.so
          path: src/main/resources/libcubiomes.so
      - name: Capture shared library (macos-latest)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: libcubiomes.dylib
          path: src/main/resources/libcubiomes.dylib
      - name: Capture shared library (windows-latest)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: cubiomes.dll
          path: src/main/resources/cubiomes.dll

  build:
    name: Build SeedMapper
    needs: compile-cubiomes
    runs-on: ubuntu-latest
    env:
      LLVM_HOME: /usr/lib/llvm-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Capture shared library
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: src/main/resources/
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'temurin'
      - name: Make Gradle wrapper executable
        run: |
          chmod +x ./gradlew
          chmod +x ./jextract/gradlew
      - name: Install LLVM 13
        run: |
          wget --no-verbose https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz
          tar -xf clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz
          sudo mv clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04 $LLVM_HOME
      - name: Compile jextract
        working-directory: jextract
        run: ./gradlew --stacktrace -Pjdk_home=$JAVA_HOME -Pllvm_home=$LLVM_HOME clean verify
      - name: Build
        run: ./gradlew build
      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SeedMapper
          path: build/libs/
